Use namespace-aware XML matching
mitre/pact-specification pull request #1
Opened 2020-04-10 14:58 UTC by asteffey

Propose a namespace-aware approach to compare XML node names.

Add test cases for namespace-aware XML matching.

2020-04-13 17:44 UTC, alilleybrinker requested changes
So this is 1) a change to the specification defining how namespace-aware matching will be done, and 2) a selection of test cases which will verify consistency with the change, to be followed up with the implementation work.

With the exception of one typo (noted for change), this looks good to me! 😄

2020-04-13 17:44 UTC, alilleybrinker commented on README.md
> +and optional prefix (e.g., `prefix:local`). Unnamspaced nodes with different full node names (e.g., `<foo/>`, `<a:foo/>`, `<b:foo/>`) won't match.
"Unnamspaced" -> "Un-namespaced"

2020-04-13 20:04 UTC, jstandard approved these changes

2020-04-14 15:54 UTC, asteffey commented on README.md
> +and optional prefix (e.g., `prefix:local`). Unnamspaced nodes with different full node names (e.g., `<foo/>`, `<a:foo/>`, `<b:foo/>`) won't match.
Good catch, fixed in a197e67

2020-04-14 18:39 UTC, alilleybrinker approved these changes

2020-04-15 15:24 UTC, closed without merging